add workflow step to publish a release

diff --git a/.github/workflows/ipfs-deploy.yml b/.github/workflows/ipfs-deploy.yml
--- a/.github/workflows/ipfs-deploy.yml
+++ b/.github/workflows/ipfs-deploy.yml
@@ -65,3 +65,71 @@ jobs:
       - name: Publish to nft.storage
         run: |
           docker run -e NFTSTORAGE_API_KEY=${{ secrets.NFTSTORAGE_API_KEY }} $IMAGE_RELEASE_ID nft.storage
+
+      - name: Create a release
+        if: startsWith(github.ref, 'refs/tags/')
+        env:
+          REF_NAME: ${{ github.ref_name }}
+          GITHUB_REPOSITORY: ${{ github.repository }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          # Markdown template for the release notes
+          RELEASE_NOTE_TEMPLATE=$(cat << EOF
+          #### IPFS Hash
+
+          \`\`\`
+          $IPFS_HASH
+          \`\`\`
+
+          You can view published versions of Lunaria through any IPFS Gateway
+
+          [ipfs://$IPFS_HASH](ipfs://$IPFS_HASH) __(Recommended)__
+          _requires Brave Browser or IPFS Desktop_
+          [https://$IPFS_HASH.ipfs.nftstorage.link](https://$IPFS_HASH.ipfs.nftstorage.link)
+          [https://$IPFS_HASH.ipfs.zoltu.io](https://$IPFS_HASH.ipfs.zoltu.io)
+          [https://$IPFS_HASH.ipfs.keydonix.com](https://$IPFS_HASH.ipfs.keydonix.com)
+          [https://$IPFS_HASH.ipfs.cf-ipfs.com](https://$IPFS_HASH.ipfs.cf-ipfs.com)
+          [https://$IPFS_HASH.ipfs.w3s.link](https://$IPFS_HASH.ipfs.w3s.link)
+          EOF
+          )
+
+          # Generate payload for creating a new release
+          PAYLOAD_TEMPLATE=$(cat <<EOF
+          {
+            "name": "$REF_NAME",
+            "tag_name": "$REF_NAME",
+            "target_commitish": "main",
+            "body": $(echo "$RELEASE_NOTE_TEMPLATE" | jq -cRs '@json|fromjson'),
+            "draft": false,
+            "generate_release_notes": true
+          }
+          EOF
+          )
+
+          # Create a github release
+          # https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release
+          REQUEST_DATA=$(echo "$PAYLOAD_TEMPLATE" | jq -c)
+          RESPONSE=$(curl \
+            --silent \
+            --location \
+            --request POST \
+            --header "Accept: application/vnd.github+json" \
+            --header "Authorization: Bearer $GITHUB_TOKEN" \
+            --header "X-GitHub-Api-Version: 2022-11-28" \
+            --data "$REQUEST_DATA" \
+            --write-out "%{http_code}" \ # append the status code to response
+            https://api.github.com/repos/$GITHUB_REPOSITORY/releases
+          )
+
+          # Extract the response body and the appended http code
+          RESPONSE_CODE=${RESPONSE: -3}
+          RESPONSE_BODY=${RESPONSE//$RESPONSE_CODE/}
+
+          # Successful creation will return a status 201 (Created), otherwise show the error
+          if [ "$RESPONSE_CODE" -ne  201 ]; then
+            ERROR_MESSAGE=$(echo "$RESPONSE_BODY" | jq '.message')
+            echo "HTTP $RESPONSE_CODE - $ERROR_MESSAGE"
+            exit 1
+          fi
+
+          echo "Release ($REF_NAME) successfully created"
